quarkus.swagger-ui.path=swagger-ui
quarkus.swagger-ui.always-include=true	

quarkus.container-image.build=true
quarkus.container-image.push=true

%prod.quarkus.rest-client."ollama-api".url=http://172.17.0.1:11434
%test.quarkus.rest-client."ollama-api".url=http://localhost:11434

